name: radiguru
description: "A medical social media application"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.10.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

  # UI
  cupertino_icons: ^1.0.8
  google_fonts: ^4.0.4
  flutter_svg: ^1.1.2
  shimmer: ^3.0.0
  lottie: ^2.7.0
  cached_network_image: ^3.3.1
  flutter_switch: ^0.3.2
  carousel_slider: ^4.2.1
  flutter_staggered_grid_view: ^0.7.0
  photo_view: ^0.14.0
  video_player: ^2.8.1
  chewie: ^1.7.4
  url_launcher: ^6.2.2
  share_plus: ^7.2.2
  flutter_quill: ^8.5.0
  intl_phone_field: ^3.1.0
  country_pickers: ^3.0.1
  flutter_contacts: ^1.1.7+4
  file_picker: ^8.1.7
  image_picker: ^1.0.7
  image: ^4.1.3
  video_thumbnail: ^0.5.3
  timeago: ^3.6.3
  hooks_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.5
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  uuid: ^4.2.2
  equatable: ^2.0.5
  dartz: ^0.10.1
  get_it: ^7.6.7
  injectable: ^2.1.4
  logger: ^2.0.2
  dio: ^5.3.2
  pretty_dio_logger: ^1.3.1
  connectivity_plus: ^5.0.2
  flutter_secure_storage: ^8.0.0
  shared_preferences: ^2.2.2
  google_sign_in: ^6.1.6
  sign_in_with_apple: ^5.0.0
  supabase_flutter: ^2.3.4
  flutter_riverpod: ^2.4.9
  flutter_local_notifications: ^17.2.3
  timezone: ^0.9.2
  package_info_plus: ^8.1.2
  device_info_plus: ^9.1.2
  path_provider: ^2.1.1
  path: ^1.8.3
  permission_handler: ^11.1.0
  flutter_dotenv: ^5.1.0
  flutter_facebook_auth: ^5.0.8
  sentry_flutter: ^7.11.0
  flutter_screenutil: ^5.9.0
  scroll_to_index: ^3.0.1
  pull_to_refresh: ^2.0.0
  infinite_scroll_pagination: ^4.0.0
  keyboard_dismisser: ^2.0.0
  country_code_picker: ^3.0.0
  # contacts_service: ^0.6.3  # Commented out due to namespace issues
  flutter_html: ^3.0.0-beta.2
  webview_flutter: ^4.4.2
  webview_flutter_android: ^4.0.0
  webview_flutter_wkwebview: ^3.8.4
  flutter_cache_manager: ^3.3.1
  transparent_image: ^2.0.0
  mime: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.6
  riverpod_generator: ^2.3.10
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  injectable_generator: ^2.1.5
  mockito: ^5.4.4
  mocktail: ^1.0.3
  change_app_package_name: ^1.1.0
  flutter_flavorizr: ^2.2.1
  flutter_native_splash: ^2.3.5
  flutter_launcher_icons: ^0.13.1
  very_good_analysis: ^5.1.0
  lint: ^1.6.0
  analyzer: ^7.6.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"
  web:
    generate: true
    image_path: "assets/images/app_icon_web.png"
  windows:
    generate: true
    image_path: "assets/images/app_icon_windows.png"
  macos:
    generate: true
    image_path: "assets/images/app_icon_macos.png"
  linux:
    generate: true
    image_path: "assets/images/app_icon_linux.png"

flutter_native_splash:
  color: "#FFFFFF"
  image: "assets/images/splash_logo.png"
  android_12:
    image: "assets/images/splash_logo.png"
    icon_background_color: "#FFFFFF"
  web: true

flutter_intl:
  enabled: true
  class_name: "S"
  main_locale: "en"
  arb_dir: "lib/l10n"
  output_dir: "lib/generated/l10n"
  use_deferred_loading: true
  synthetic_package: false

flutter_gen:
  output: lib/gen/
  line_length: 80
  integrations:
    flutter_svg: true
    rive: false
    lottie: true

  assets:
    enabled: true
    package_parameter_enabled: true
    style: snake

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/animations/
    - assets/fonts/
    - assets/translations/
    - .env

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

dependency_overrides:
  flutter_keyboard_visibility: ^6.0.0
