name: app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.3.5
  supabase_flutter: ^2.12.0
  image_picker: ^1.2.1
  flutter_secure_storage: ^10.0.0
  google_sign_in: ^7.2.0
  uuid: ^4.5.2
  intl: ^0.20.2
  cached_network_image: ^3.4.1
  lottie: ^3.3.2
  shimmer: ^3.0.0
  video_player: ^2.10.1
  mime: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.8
  riverpod_generator: ^2.3.10

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
